# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-12 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast_show',
            name='show_id',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='podcast_show',
            name='show_format',
            field=models.CharField(choices=[('Audioplay', 'Audioplay'), ('Unscripted', 'Unscripted')], max_length=20),
        ),
    ]
