# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 05:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_podcast_show_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast_show',
            name='user',
        ),
    ]
