# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 22:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collection', '0003_remove_podcast_show_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast_post',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
