# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 05:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_podcast_show_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast_show',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
