# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 05:10
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_auto_20170517_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast_post',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
