# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 02:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_auto_20170517_0510'),
    ]

    operations = [
#        migrations.RenameModel(
#            old_name='podcast_show',
#            new_name='podcast_post',
#        ),
    ]
