# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0008_auto_20170522_0256'),
    ]

    operations = [
        migrations.CreateModel(
            name='podcast_show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_name', models.CharField(max_length=255)),
                ('show_description', models.TextField()),
                ('show_website', models.CharField(max_length=100)),
                ('show_slug', models.SlugField(unique=True)),
                ('show_format', models.CharField(choices=[('Scripted', 'Scripted'), ('Talk', 'Talk')], max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='podcast_post',
            old_name='description',
            new_name='post_content',
        ),
        migrations.RenameField(
            model_name='podcast_post',
            old_name='name',
            new_name='post_title',
        ),
        migrations.AddField(
            model_name='podcast_post',
            name='last_modified',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='podcast_post',
            name='podcast_show_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.podcast_show'),
        ),
    ]
