# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 22:10
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('collection', '0009_auto_20170522_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast_show',
            name='show_tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
