# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-24 03:48
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0010_podcast_show_show_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast_post',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Post Tags'),
        ),
        migrations.AlterField(
            model_name='podcast_show',
            name='show_tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Show Tags'),
        ),
    ]
