# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-24 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0011_auto_20170524_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast_post',
            name='last_modified',
            field=models.DateField(auto_now=True),
        ),
    ]
